backend:
  name: git-gateway
  branch: main
media_folder: "public/assets/img" # Media files will be stored in the repo under static/images/uploads
public_folder: "/assets/img" # The src attribute for uploaded media will begin with /images/uploads
# Please run "npx netlify-cms-proxy-server" for local backend

# This line allow to test the admin panel on the local newtwork
# For the production, please remove this line
local_backend: true

editor:
  preview: true
publish_mode: editorial_workflow
collections:
  - name: "blog"
    label: "Blog"
    folder: "src/articles"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Image description", name: "imageAlt", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  # This are the configs for the  site
  - name: "settings"
    label: "Settings"
    editor:
      preview: false
    files:
      - label: "NavLinks"
        name: "links"
        file: "src/_data/navlinks.yml"
        fields:
          - label: Nav Items
            name: links
            widget: list
            allow_add: true
            collapsed: false
            fields:
              - { label: "Location", name: "title", widget: "string" }
              - {
                  label: "URL",
                  name: "url",
                  widget: "string",
                  default: "/pages",
                }

      - label: "Branding"
        name: "branding"
        file: "src/_data/branding.yml"
        fields:
          - { label: "Brand", name: "brand", widget: "string" }
          - { label: "Site Description", name: "description", widget: "string" }
          - { label: "Intro", name: "intro", widget: "string" }
          - { label: "Logo", name: "logo", widget: "image", required: false }
          - {
              label: "Logo Alt",
              name: "logoAlt",
              widget: "string",
              required: false,
            }
          - label: "Links for Social Media"
            name: "links"
            widget: list
            allow_add: true
            collapsed: false
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }
      - label: "Colors"
        name: "Colors"
        file: "src/_data/colors.json"
        fields:
          - {
              label: "Modified",
              name: "modified",
              widget: "boolean",
              default: true,
            }
          - { label: "Primary", name: "primary", widget: "color" }
          - { label: "secondary", name: "secondary", widget: "color" }
